# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
from datetime import date


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "NOM DU PROJET"
project_short_name = "nom-projet"
author = 'Vincent Férotin'

today = date.today()
copyright = '{}, {}'.format(today.year, author)

# The short X.Y version
version = '0'
# The full version, including alpha/beta/rc tags
release = '{} - {}'.format(version, today.isoformat())


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]
# and their related options:

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for LaTeX output ------------------------------------------------

latex_engine = 'lualatex'
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    #'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    #'preamble': '',

    # Additional document content (right before the indices).
    #
    #'atendofbody': '',

    # Latex figure (float) alignment
    #
    #'figure_align': 'htbp',

    # `babel` package inclusion, default to '\\usepackage{babel}'
    # (the suitable document language string is passed as class option,
    # and english is used if no language).
    # With LuaLaTeX, Sphinx configures the LaTeX document to use polyglossia:
    # '\\usepackage{polyglossia}'.
    #
    #'babel': '\\usepackage{polyglossia}',

    # Inclusion of the `fncychap` package (which makes fancy chapter titles),
    # default to '\\usepackage[Sonny]{fncychap}' for internationalized docs.
    # Other `fncychap` styles you can try are 'Bjarne' for english doc.,
    # 'Lenny', 'Glenn', 'Conny', 'Rejne' and 'Bjornstrup'.
    # You can also set this to '' to disable fncychap.
    #
    #'fncychap': '\\usepackage[Sonny]{fncychap}',

    # Value that prefixes 'release' element on title page, default 'Release'.
    # As for title and author used in the tuples of latex_documents,
    # it is inserted as LaTeX markup.
    #
    'releasename': 'Version',

    # `tableofcontents` call, default '\\sphinxtableofcontents'
    # (it is a wrapper of unmodified \tableofcontents, which may itself
    # be customized by user loaded packages).
    # Override if you want to generate a different table of contents or
    # put content between the title page and the TOC, or disable TOC insertion.
    #
    #'tableofcontents': '\\sphinxtableofcontents',

    # `printindex` call, the last thing in the file, default '\\printindex'.
    # Override if you want to generate the index differently or append
    # some content after the index.
    # For example '\\footnotesize\\raggedright\\printindex' is advisable
    # when the index is full of long entries.
    #
    #'printindex': '\\printindex',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class],
#  toctree_only).
latex_documents = [
    (master_doc, '{}.tex'.format(project_short_name), project,
     author, 'manual', False),
]

# Add page references after internal references.
# This is very useful for printed copies of the manual. Default is False.
latex_show_pagerefs = True

# Control whether to display URL addresses.
# This is very useful for printed copies of the manual.
# The setting can have the following values:
# - 'no': do not display URLs (default)
# - 'footnote': display URLs in footnotes
# - 'inline': display URLs inline in parentheses
latex_show_urls = 'footnote'

# Use `xindy` rather than makeindex for preparing the index of general terms
# (from index usage). This means that words with UTF-8 characters will get
# ordered correctly for the language.
# True is recommended for non-English documents as soon as some indexed terms
# use non-ascii characters from the language script.
latex_use_xindy = True  # True by default if `latex_engine is 'lualatex'


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, project_short_name, project,
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, project_short_name, project,
     author, project_short_name, 'One line description of project.',
     'Miscellaneous'),
]

